name: apply-taxonomy
on: { workflow_dispatch: {} }
jobs:
  run:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install PyGithub pyyaml
      - name: Apply taxonomy
        env: { GH_TOKEN_W: ${{ secrets.GH_TOKEN_W }} }
        run: python scripts/apply_taxonomy.py